name: Frogbot Scan

on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Frogbot Scan Maven Example Only
        uses: jfrog/frogbot@v2
        with:
          command: scan-pull-request
          target: "maven-examples"  # scan only Maven project
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

